files:
  - source: /common/src/main/resources/assets/**/lang/en_us.json
    translation: /common/src/main/resources/assets/**/lang/%locale_with_underscore%.json
    translation_replace:
      af_ZA: af_za
      ar_SA: ar_sa
      ast_ES: ast_es
      az_AZ: az_az
      ba_RU: ba_ru
      bar: bar
      be_BY: be_by
      bg_BG: bg_bg
      br_FR: br_fr
      brb: brb
      bs_BA: bs_ba
      ca_ES: ca_es
      cs_CZ: cs_cz
      cy_GB: cy_gb
      da_DK: da_dk
      de_AT: de_at
      de_CH: de_ch
      de_DE: de_de
      el_GR: el_gr
      en_AU: en_au
      en_CA: en_ca
      en_GB: en_gb
      en_NZ: en_nz
      en_PT: en_pt
      en_UD: en_ud
      en_us: en_us
      enp: enp
      enws: enws
      eo_UY: eo_uy
      es_AR: es_ar
      es_CL: es_cl
      es_EC: es_ec
      es_ES: es_es
      es_MX: es_mx
      es_UY: es_uy
      es_VE: es_ve
      esan: esan
      et_EE: et_ee
      eu_ES: eu_es
      fa_IR: fa_ir
      fi_FI: fi_fi
      fil_PH: fil_ph
      fo_FO: fo_fo
      fr_CA: fr_ca
      fr_FR: fr_fr
      fra_DE: fra_de
      fur_IT: fur_it
      fy_NL: fy_nl
      ga_IE: ga_ie
      gd_GB: gd_gb
      gl_ES: gl_es
      haw_US: haw_us
      he_IL: he_il
      hi_IN: hi_in
      hr_HR: hr_hr
      hu_HU: hu_hu
      hy_AM: hy_am
      id_ID: id_id
      ig_NG: ig_ng
      io_EN: io_en
      is_IS: is_is
      it_IT: it_it
      ja_JP: ja_jp
      jbo_EN: jbo_en
      ka_GE: ka_ge
      kk_KZ: kk_kz
      kn_IN: kn_in
      ko_KR: ko_kr
      ksh: ksh
      kw_GB: kw_gb
      la_LA: la_la
      lb_LU: lb_lu
      li_LI: li_li
      lmo: lmo
      lol_US: lol_us
      lt_LT: lt_lt
      lv_LV: lv_lv
      lzh: lzh
      mk_MK: mk_mk
      mn_MN: mn_mn
      ms_MY: ms_my
      mt_MT: mt_mt
      nb_NO: no_no
      nds_DE: nds_de
      nl_BE: nl_be
      nl_NL: nl_nl
      nn_NO: nn_no
      oc_FR: oc_fr
      pl_PL: pl_pl
      pt_BR: pt_br
      pt_PT: pt_pt
      qya_AA: qya_aa
      ro_RO: ro_ro
      rpr: rpr
      ru_RU: ru_ru
      ry_UA: ry_ua
      se_NO: se_no
      sk_SK: sk_sk
      sl_SI: sl_si
      so_SO: so_so
      sq_AL: sq_al
      sr_SP: sr_sp
      sv_SE: sv_se
      sxu: sxu
      szl: szl
      ta_IN: ta_in
      th_TH: th_th
      tl_PH: tl_ph
      tlh_AA: tlh_aa
      tok: tok
      tr_TR: tr_tr
      tt_RU: tt_ru
      uk_UA: uk_ua
      val_ES: val_es
      vec_IT: vec_it
      vi_VN: vi_vn
      yi_DE: yi_de
      yo_NG: yo_ng
      zh_CN: zh_cn
      zh_HK: zh_hk
      zh_TW: zh_tw
